(function(){"use strict";
const RANKS=["2","3","4","5","6","7","8","9","10","J","Q","K","A"],SUITS=["♠","♥","♦","♣"];
const $=s=>document.querySelector(s),wait=n=>new Promise(r=>setTimeout(r,n)),sound=n=>window.PocketSound?.play(n);
const ui={chips:$("#chips"),round:$("#round"),min:$("#minimum"),pot:$("#pot"),cpu:$("#cpu-hand"),player:$("#player-hand"),cpuAction:$("#cpu-action"),yourHand:$("#your-hand"),bet:$("#bet"),down:$("#bet-down"),up:$("#bet-up"),status:$("#status"),action:$("#action"),start:$("#start-key"),mode:$("#mode")};
let chips=200,round=0,minBet=1,pot=0,wager=0,deck=[],player=[],cpu=[],marked=[],cursor=0,phase="idle",busy=false,token=0;
function freshDeck(){const cards=SUITS.flatMap((s,si)=>RANKS.map((r,ri)=>({s,r,v:ri+2,red:si===1||si===2})));for(let i=cards.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]]}return cards}
function evalHand(cards){const vs=cards.map(c=>c.v).sort((a,b)=>a-b),desc=[...vs].sort((a,b)=>b-a),counts=new Map();vs.forEach(v=>counts.set(v,(counts.get(v)||0)+1));const groups=[...counts].sort((a,b)=>b[1]-a[1]||b[0]-a[0]),flush=cards.every(c=>c.s===cards[0].s),wheel=vs.join()==="2,3,4,5,14",straight=wheel||vs.every((v,i)=>i===0||v===vs[i-1]+1),straightHigh=wheel?5:desc[0];let rank,name,tie;if(straight&&flush){[rank,name,tie]=[8,"STRAIGHT FLUSH",[straightHigh]]}else if(groups[0][1]===4){[rank,name,tie]=[7,"FOUR OF A KIND",[groups[0][0],groups[1][0]]]}else if(groups[0][1]===3&&groups[1][1]===2){[rank,name,tie]=[6,"FULL HOUSE",[groups[0][0],groups[1][0]]]}else if(flush){[rank,name,tie]=[5,"FLUSH",desc]}else if(straight){[rank,name,tie]=[4,"STRAIGHT",[straightHigh]]}else if(groups[0][1]===3){[rank,name,tie]=[3,"THREE OF A KIND",[groups[0][0],...groups.slice(1).map(g=>g[0]).sort((a,b)=>b-a)]]}else if(groups[0][1]===2&&groups[1][1]===2){const pairs=[groups[0][0],groups[1][0]].sort((a,b)=>b-a);[rank,name,tie]=[2,"TWO PAIR",[...pairs,groups[2][0]]]}else if(groups[0][1]===2){[rank,name,tie]=[1,"ONE PAIR",[groups[0][0],...groups.slice(1).map(g=>g[0]).sort((a,b)=>b-a)]]}else{[rank,name,tie]=[0,"HIGH CARD",desc]}return{rank,name,tie}}
function compare(a,b){let x=evalHand(a),y=evalHand(b);if(x.rank!==y.rank)return x.rank-y.rank;for(let i=0;i<Math.max(x.tie.length,y.tie.length);i++)if((x.tie[i]||0)!==(y.tie[i]||0))return(x.tie[i]||0)-(y.tie[i]||0);return 0}
function cardEl(c,i,owner){let b=document.createElement("button");b.className="playing-card"+(c?.red?" red":"")+(owner==="cpu"&&phase!=="result"?" back":"")+(owner==="player"&&marked[i]?" selected":"");b.disabled=owner!=="player"||phase!=="draw";b.innerHTML=c?`<span>${c.r}</span><span class="suit">${c.s}</span>`:"";if(owner==="player")b.onclick=()=>{cursor=i;toggle()};return b}
function label(){return phase==="idle"?"DEAL":phase==="draw"?(marked.some(Boolean)?"CHANGE":"STAND"):phase==="bet"?"SHOW DOWN":phase==="result"?"NEXT":"WAIT"}
function render(){ui.chips.textContent=chips;ui.round.textContent=`ROUND ${String(round).padStart(2,"0")}`;ui.min.textContent=`MIN BET ${minBet}`;ui.pot.textContent=`POT ${pot}`;ui.bet.textContent=wager;ui.player.replaceChildren(...player.map((c,i)=>cardEl(c,i,"player")));ui.cpu.replaceChildren(...cpu.map((c,i)=>cardEl(c,i,"cpu")));ui.yourHand.textContent=player.length?evalHand(player).name:"NO HAND";ui.action.textContent=label();ui.start.textContent=label();ui.mode.textContent=phase==="bet"?`BET ${wager}`:`MIN ${minBet}`;ui.down.disabled=phase!=="bet"||wager<=minBet;ui.up.disabled=phase!=="bet"||wager>=chips}
async function deal(){if(busy)return;if(chips<Math.max(1,Math.floor(round/3)+1)){chips=200;round=0}busy=true;round++;minBet=Math.min(20,1+Math.floor((round-1)/3));let ante=Math.min(minBet,chips);chips-=ante;pot=ante*2;deck=freshDeck();player=deck.splice(0,5);cpu=deck.splice(0,5);marked=Array(5).fill(false);cursor=0;phase="draw";ui.cpuAction.textContent="HIDDEN";ui.status.textContent="カードをタップ、または十字＋Aで交換選択。STARTをタップ、またはSで確定";sound("deal");busy=false;render()}
function cpuMarks(){let counts=new Map();cpu.forEach(c=>counts.set(c.v,(counts.get(c.v)||0)+1));let made=[...counts.values()].some(n=>n>1);return cpu.map(c=>made?counts.get(c.v)===1:c.v<12)}
async function exchange(){if(phase!=="draw"||busy)return;busy=true;let cm=cpuMarks();for(let i=0;i<5;i++)if(marked[i])player[i]=deck.shift();for(let i=0;i<5;i++)if(cm[i])cpu[i]=deck.shift();ui.cpuAction.textContent=cm.some(Boolean)?`CHANGE ${cm.filter(Boolean).length}`:"STAND";sound("flip");await wait(500);phase="bet";wager=Math.min(minBet,chips);ui.status.textContent="±をタップ、または十字/SELECTでBET。STARTをタップ、またはSで勝負";busy=false;render()}
function changeBet(d){if(phase!=="bet")return;wager=Math.max(minBet,Math.min(chips,wager+d*minBet));sound("move");render()}
async function showdown(){if(phase!=="bet"||busy)return;busy=true;chips-=wager;pot+=wager*2;let strength=evalHand(cpu).rank,cpuFold=strength===0&&wager>minBet*3&&Math.random()<.45;if(cpuFold){chips+=pot;phase="result";ui.cpuAction.textContent="FOLD";ui.status.textContent=`CPU FOLD — YOU WIN +${pot}`;sound("win");busy=false;render();return}phase="result";let result=compare(player,cpu);if(result>0){chips+=pot;ui.status.textContent=`YOU WIN! +${pot}`;sound("win")}else if(result<0){ui.status.textContent="YOU LOSE";sound("lose")}else{chips+=Math.floor(pot/2);ui.status.textContent="DRAW — POT SPLIT";sound("coin")}ui.cpuAction.textContent=evalHand(cpu).name;busy=false;render()}
function fold(){if(!["draw","bet"].includes(phase))return;phase="result";ui.status.textContent="YOU FOLD";ui.cpuAction.textContent="WIN";sound("back");render()}
function toggle(){if(phase!=="draw")return;marked[cursor]=!marked[cursor];sound("hold");render()}
function action(){if(phase==="idle"||phase==="result")deal();else if(phase==="draw")exchange();else if(phase==="bet")showdown()}
ui.action.onclick=action;ui.down.onclick=()=>changeBet(-1);ui.up.onclick=()=>changeBet(1);document.addEventListener("pocket-input",e=>{let a=e.detail.action;if(phase==="draw"&&["left","up"].includes(a)){cursor=(cursor+4)%5;render()}else if(phase==="draw"&&["right","down"].includes(a)){cursor=(cursor+1)%5;render()}else if(phase==="bet"&&["left","down"].includes(a))changeBet(-1);else if(phase==="bet"&&["right","up","select"].includes(a))changeBet(1);else if(a==="a")phase==="draw"?toggle():phase==="bet"?showdown():action();else if(a==="b")fold();else if(a==="start")action();else if(a==="select"&&phase!=="bet"){} });render();
})();
